[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# llama
> mmd.emoticon=`tree`


## llama 3\.1李沐

### 预训练一般不会自己做，没有这个能力，<br/> 而且微调才是一般人用的

### 任务

#### 多语言、 代码、工具使用、推理

### 支持 128K 上下文

#### 宣传需要，可以做到100万 token 或者 无限大token

##### 但是实际32K已经够用了

### 发布llama gurd3 安全模型，对输出进行改写

### llama当前大模型主要分为2阶段

#### 预训练

##### next\-token预测

###### GPT123

#### 后训练

##### 微调

###### SFT和预训练没有区别， 除了，数据集是监督的

##### 对齐

###### DPO

####### RS拒绝采样

##### 特定下游任务改进

### llama系列喜欢堆数据

#### 已经堆到15T的数据了

##### 公共网络上抓到文本的上限

#### 虽然可以把数据变得更大，但是， 将数据清洗干净，把数据质量变得更好

### 没有使用MOE，其他模型厂喜欢使用MOE， 

#### 学术角度，可能需要卷高级方法

#### llama MOE 没做好， 所以只发 非Moe

##### 而且复杂的强化学习算法也效果不好，所以，发布了简单的DPO

### llama模型调教的很一般，导致 评估的时候喜欢，用 few\-shot （自己调，总是找对自己友好的）、 <br/>zero\-shot COT。<br/>实际上评估最好就是zero\-shot直接评估，所以比较取巧

#### MMLU 选择题

##### 模型的记忆题目能力

###### 模型越大记忆能力越好

##### 70B 比 405B 低 4%

#### IFEval 指令遵循能力

##### 70B 与 405B差距不明显

#### 写代码

#### 数学能力

#### 推理

#### 工具使用

#### 长上下文

#### 多语言

#### 总结

##### llama3 70B 和 llama3 405B ，是多个任务上 性能差别只有2%\-4%差距<br/>而且，405B的模型推理速度更慢

##### 405B 推理和训练成本很大

###### 推理时，8卡H100 ，每秒钟 30token

####### 很贵

##### 一般70B够用了

###### 70B 比8B性能高得多

### 工具使用

#### 模型写代码， 执行得到结果， 将结果插入提示语

##### 就是 agent类似

#### Mistral 100B 模型，llama发布后3天， 就发布， <br/>针对llama，100B比405B写代码能力强很多，数学也比llama好

### 技术细节

#### 数据

##### 数据质量要高

###### 去除成人数据、  和  个人信息类数据

####### 邮箱、 号码、 家庭住址

####### 但是 llama3 有成人内容， 有这个能力

###### Markdown格式数据的mark，对llama模型训练有害

###### 去重， 60%\-80% ，按照url去重

####### minhash 去重重复文本

###### dirty word去除

####### 算文档 和 正常文档的 KL div ，差太远就去掉

####### 苦力

###### 上述处理，处理完 100万美金

##### deepseek论文 发现， 使用了代码数据， 模型的推理能力就会很强

##### 将数据分类

###### 知识类

###### 娱乐类

####### 减少

###### 通用知识

####### 大模型更容易记住知识

###### 多语言

####### llama 比商用模型的 多语言能力较弱

##### 数据退火训练

###### 在高质量的数学题目数据、 进行退火

####### 帮助预训练模型，能够提升 基准分数

###### 数据少

####### SFT只能放一部分

######## 几十到几百万条

####### 还需要退火调整学习率

##### 混合比例

##### llama讲得不详细
