[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 分布式训练

## 用 1 张显卡训练 LLM，以下是一些对显卡的主要要求

### 显存

#### 7B的参数，需要4090ti 24 GB

#### 需要装在

##### 模型参数

##### 优化器的 一阶 和 二阶 梯度参数

### 计算

#### cuda核心

##### cuda核心越多并行能力越强

###### A100 有 6\.9k个 cuda核心

#### 浮点数计算

##### 梯度计算、梯度更新都是浮点数运算

##### FP32、 FP16、 BP16等 浮点数运算越快， 显存需要留存的参数越少

### 内存带宽

#### 显存 和 计算核心 之间的管道

### 稳定性

#### 散热

#### 故障率
