[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 20\-大模型外挂知识库优化——<br/>负样本样本挖掘篇
> mmd.emoticon=`tree`


## 为何需要构建负样本

### 为训练好一个高质量的检索模型，

### 往往需要从大量的候选样本集合中采样高质量的负例，<br/>配合正例一起进行训练

## 如何构造负样本

### 2\.1 随机采样策略（Random Sampling）方法

####  方法：

##### 直接基于一均匀分布从所有的候选Document中

##### 随机抽取Document作为负例；

#### • 存在问题：

##### 由于无法保证采样得到的负例的质量，<br/>故经常会采样得到过于简单的负例

##### 其不仅无法给模型带来有用信息

##### 还可能导致模型过拟合，进而无法区分某些较难的负例样本

#### 对梯度影响

##### 挖掘负例训练时，由于其采样得到的负例往往过于简单，<br/>其会导致该分数接近于零,<br/>进而导致梯度趋近于0， 

###### 过于小的梯度均值会导致模型不易于收敛

### 2\.2 Top\-K负例采样策略<br/>（Top\-K Hard Negative Sampling）方法

#### • 方法：

##### 基于一稠密检索模型， 对所有候选Document与Query<br/>计算匹配分数

##### 然后直接选择其中 Top\-K的候选Document作为负例

#### 优点：

##### 可以保证采样得到的负例，<br/>是模型，<br/>未能较好区分的较难负例；

#### • 存在问题：

##### 很可能将潜在的正例也误判为负例，<br/>即假负例（False Negative）。

##### 如果训练模型去将该部分假负例与正例区分开来，<br/>反而会导致模型<br/>无法准确衡量Query\-Document的语义相似度

#### 对梯度的影<br/>响：

##### 由于其很容易采样得到语义与正例一致的假负例，

##### 其会导致梯度正负样本的右项值相似，但是左项符号相反，<br/>这样会导致计算得到的梯度方差很大，同样导致模型训练不稳定

### 2\.3 困惑负样本采样方法SimANS 方法

#### • 动机：

##### 在所有负例候选中，<br/>与Query的语义相似度接近于正例的负例

##### 可以同时具有较大的梯度<br/>均值和较小的梯度方差，是更加高质量的困惑负样本

#### • 方法：

##### 对与正例语义相似度接近的困惑负例样本进行采样

#### • 采样方法特点：

##### • 与Query无关  的Document应被赋予较低的相关分数，因其可提供的信息量不足；

##### • 与Query很可能相关  的Document应被赋予较低的相关分数，因其可能是假负例；

##### • 与正例语义相似度接近  的Document应该被赋予较高的相关分数，因其既需要被学习，同<br/>时是假负例的概率相对较低。

#### • 困惑样本采样分布

### 2\.4 利用 对比学习微调 方式构建负例方法

#### • 目的：

##### 优化向量化模型，使其向量化后的文本，<br/>相似的在向量空间距离近，不相似的在向量空<br/>间距离远。

#### • 构建方法：

##### ：如果是随机出来的话，完全可以用同一个batch里，其他问题的文档正例当作某一<br/>个问题的文档负例，如果想要效果好，还需要有比较大的batch size

##### 损失函数是基于批内负<br/>样本的交叉熵损失

#### • 实现方法：

##### 分别将B1个问题，和B2个文档片段通过向量化模型变成向量形式

##### 然后通过矩阵乘积计算每个问<br/>题和文档的相似度，最后通过交叉熵损失进行优化

### 2\.5 基于批内负采样的对比学习方法

#### • 本质：

##### ：随机选取文档负例，如果能有针对性的，找到和文档正例比较像的文档负例（模型更难<br/>区分这些文档负例），加到训练里，是有助于提高对比学习效果的

##### 就好比我们只有不断的做<br/>难题才能更好的提高考试水平。

#### • 论文方法：

##### 在文档向量空间找到和文档正例最相近的文档片段当作文档负例

##### 训练向量化模<br/>型。模型更新一段时间后，刷新文档向量，<br/>寻找新的文档负例，继续训练模型。

### 2\.6 相同文章采样方法

#### • 思路：

##### 文档正例所在的文章里，其他文档片段当作难负例，

##### ，毕竟至少是属于同一主题的，和随<br/>机样本比起来比较难区分

#### • 存在问题：

##### 实际应用场景下，如果你的数据比较脏，难例挖掘用处可能不大。

### 2\.7 LLM辅助<br/>生成软标签及蒸馏

#### • 方法：

##### 是bge2提出的。

##### 对于向量化模型的训练，可以让<br/>LLM帮忙生成样本的辅助标签，引导向量化模型训练

##### 在已知LLM需要输出的标准答案下，<br/>分别将问题和各个文档片段C放入LLM的prompt中

###### 看LLM<br/>生成标准答案的概率r大小，当作辅助标签
