[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 21\-RAG（Retrieval\-Augmented Generation）<br/>评测面
> mmd.emoticon=`tree`


## 一、为什么需要 对 RAG 进行评测？

### 在探索和优化 RAG（检索增强生成器）的过程中，<br/>如何有效评估其性能已经成为关键问题。

## 二、如何合成 RAG 测试集？

### 数据集包含以下列：

#### • question（问题）：想要评估的RAG的问题

#### • ground\_truths（真实答案）：问题的真实答案

#### • answer（答案）：RAG 预测的答案

#### • contexts（上下文）：RAG 用于生成答案的相关信息列表

#### 前两列代表真实数据，最后两列代表 RAG 预测数据

### 要生成（问题、答案）元组

#### 首先需要准备 RAG 数据，我们将其拆分为块，并将其嵌入向量<br/>数据库中

#### 完成这些步骤后，我们会指示 LLM 从指定主题中生成 num\_questions 个问题

#### 为了从给定的上下文中生成问题和答案

##### 按照以下步骤操作：

###### 1\. 选择一个随机块并将其作为根上下文

###### 2\. 从向量数据库中检索 K 个相似的上下文

###### 3\. 将根上下文和其 K 个相邻上下文的文本连接起来,<br/>以构建一个更大的上下文

###### 4\. 使用这个大的上下文和 num\_questions 在以下的提示模板中,<br/>生成问题和答案

####### 您的任务是根据给定的上下文提出\{num\_questions\}个问题，并给出每个问题的答案。<br/>在每个问题的末尾加上"? <br/>提供的上下文写出该问题的答案。<br/>每个问题/答案之间用 "XXX "隔开。<br/>每个问题必须以 "question: "开头。<br/>每个答案必须以 "answer: "开头。<br/>问题必须符合以下规则：<br/>1\.即使在没有给定上下文的情况下，问题也应该对人类有意义。<br/>2\.问题应能根据给定的上下文给出完整的答案。<br/>3\.问题应从包含重要信息的上下文中提取。也可以是表格、代码等。<br/>4\.问题答案不应包含任何链接。<br/>5\.问题难度应适中。<br/>6\.问题必须合理，必须为人类所理解和回答。<br/>7\.不要在问题中使用 "提供上下文 "等短语。<br/>8\.避免在问题中使用 "和 "字，因为它可以分解成多个问题。<br/>9\.问题不应超过 10 个单词，尽可能使用缩写。<br/>
> align=`left`


###### 5\. 重复以上步骤 num\_count 次,<br/>每次改变上下文并生成不同的问题。

### 代码实例

## 三、RAG 有哪些评估方法？

### 3\.1 独立评估

#### 独立评估涉及对检索模块和生成模块（即阅读和合成信息）的评估

#### 3\.1\.2 介绍一下 独立评估 模块？

##### 生成模块

###### 是将检索到的文档与查询相结合，形成增强或合成的输入

###### 这与最终答案或响应的生成不同，后者通常采用端到端的评估方式

##### • 评估指标：

###### • 1、 答案相关性（Answer Relevancy）

####### 此指标的目标是评估生成的答案，<br/>与提供的问题提示之间的相关性

####### 这一指标通过问题和答案的结合来进行计算，

####### 评分的范围通常在<br/>0到1之间，其中高分代表更好的相关性。

###### • 2、 忠实度（Faithfulness）

####### 检查生成的答案在给定上下文中的事实准确性

####### 。评估的过程涉及到答案内容与其<br/>检索到的上下文之间的比对

######## 这一指标也使用一个介于0到1之间的数值来表示

######## 其中更高的数值意<br/>味着答案与上下文的一致性更高。

###### • 3、上下文精确度（Context Precision）

####### 评估所有在给定上下文中与基准信息相关的条目是否被正确地排序。

######## 理想情况<br/>下，所有相关的内容应该出现在排序的前部

######## 这一评价标准同样使用0到1之间的得分值来表示，其<br/>中较高的得分反映了更高的精确度。

####### 指标：

######## 命中率 \(Hit Rate\)、平均排名倒数 \(MRR\)、归一化折扣累积增益 \(NDCG\)、\*\*精确度<br/>\(Precision\)\*\*等

###### • 4、答案正确性（Answer Correctness）

####### 用于测量生成的答案与实际基准答案之间的匹配程度

####### 考虑了基准答案和生成<br/>答案的对比，其得分也通常在0到1之间

######## 较高的得分表明生成答案与实际答案的一致性更高。

### 3\.2 端到端评估

#### 3\.2\.1 介绍一下 端到端评估

##### 对 RAG 模型对特定输入生成的最终响应进行评估

##### 涉及模型生成的答案与输入查询的<br/>相关性和一致性

#### 3\.2\.2 介绍一下 端到端评估 模块？

##### 1\. 无标签的内容评估：

###### a\. 评价指标：答案的准确性、相关性和无害性

##### 2\. 有标签的内容评估：

###### a\. 评价指标：准确率 \(Accuracy\) 和精确匹配 \(EM\)

## 四、RAG 有哪些关键指标和能力？

### • 关键指标：

#### 答案的准确性、答案的相关性和上下文的相关性。

### • 关键能力：

#### 包括抗噪声能力、拒绝无效回答能力、信息综合能力和反事实稳健性

#### 为检索增强型生<br/>成设立了标准

## 五、RAG 有哪些评估框架？

### 5\.1 RAGAS

#### 基于简单手写提示的评估框架

#### 通过这些提示全自动地衡量答案的准确性、相关性<br/>和上下文相关性。

### 5\.2 ARES

#### ARES 减少了评估成本，通过使用少量的手动标注数据和合成数据，

#### 并应用预测驱动推理<br/>\(PDR\) 提供统计置信区间，提高了评估的准确性

#### • 算法原理：

##### 1\. 生成合成数据集：

###### 使用语言模型从目标语料库中的文档生成合成问题和答案

####### 创建<br/>正负两种样本。

##### 2\. 训练大语言模型 \(LLM\) 裁判：

######  对轻量级语言模型进行微调

###### 利用合成数据集训练<br/>它们以评估上下文相关性、答案忠实度和答案相关性。

##### 3\. 基于置信区间对 RAG 系统排名：

###### 使用这些裁判模型为 RAG 系统打分

###### 并结合手<br/>动标注的验证集，采用 PPI 方法生成置信区间，从而可靠地评估 RAG 系统的性能。
