[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 28\-提示学习（Prompting）篇
> mmd.emoticon=`tree`


## 提示学习（Prompting）

### 什么是 提示学习（Prompting）？

#### Prompt提供上下文和任务相关信息，以帮助模型更好地理解要求，并生成正确的输出

#### 实例一：问答任务中，

##### prompt可能包含问题或话题的描述，以帮助模型生成正确的答案

#### 实例二：在情感分析任务中

##### ，让模型做情感分类任务的做法通常是在句子前面加入前缀“该句子的情感是”即可，

##### 通过这种方式 将情感分类任务转换为一个“填空”任务，

###### 在训练过程中，BERT可以学习到这个前缀与句子情感之<br/>间的关联

###### 例如，它可以学习到“该句子的情感是积极的”和“该句子的情感是消极的”之间的差异

### 提示学习（Prompting） 有什么优点？

#### 通过最小化微调参数的数量和计算复杂度，来提高预训练模型在新任务上的性能，

#### 从而缓解大型预训练模型的训练成本。

#### 即使计算资源受限，也可以利用预训练模型的知识来迅速适应<br/>新任务，实现高效的迁移学习
> align=`left`


### 提示学习（Prompting）有哪些方法

####  前缀微调（Prefix\-tining）篇

##### step 1Prefix构建

###### 在输入token之前构造一段任务相关的virtual tokens作为Prefix；

##### step 2训练时只更新Prefix部分的参数

###### 而Transformer中的其他部分参数固定；

##### step 3在Prefix层前面加了MLP结构

###### \(相当于将Prefix分解为更小维度的Input与MLP的组合后输出的结果\)，

###### 训练完成后，只保留Prefix的参数

###### （用于 防止直接更新Prefix的参数导致训练不稳定的情况）

#####  前缀微调（Prefix\-tining）的优点是什么？

###### 前缀微调（Prefix\-tining） vs 人工设计离散的 Prompts 无法更新参数

####### 前缀微调（Prefix\-tining） 可以学习<br/>的“隐式”的 Prompts；

###### 基于前缀的架构可以在一个批次中处理来自多个用户/任务的样本

####### 这是其他轻量级微调方法所不能做到的；

###### vs full fine\-tuning：

####### full fine\-tuning 更新所有参数，Prefix Tuning 只更新Prefix部分的参数；

##### 前缀微调（Prefix\-tining）的缺点是什么？

###### 占用序列长度。有一定的额外计算开销;

###### 在每层都加了prompt的参数，改动较大;

#### 指示微调（Prompt\-tuning）思路是什么？

##### 前缀微调，是在 输入前面， 增加 P前缀参数

###### 可以在任意层的输入增加

##### 指示微调，是在 prompt输入 的任意位置添加 微调参数，

###### 且仅在token输入层 增加

##### 思路

###### 只在输入层加入prompt tokens，并且不需要加入 MLP 进行调整来解决难训练的问题；

####### 通过反向传播更新参数来学习prompts，而<br/>不是人工设计prompts

####### 人工设计的prompts， 是不用添加任何参数的prompt 微调，让大模型学习某个任务

###### 冻结模型原始权重，只训练prompts参数，训练完成后，只用同一个模型可以做多任务推理；

###### 可以使用 LSTM 建模 prompt 向量间 关联性

##### 指示微调（Prompt\-tuning）优点是什么？

###### 只在输入层加入prompt tokens，并且不需要加入 MLP 进行调整来解决难训练的问题

###### 随着预训练模型参数量的增加，Prompt Tuning的方法会逼近全参数微调的结果

###### 提出了prompt ensembling：在一个批次（Batch）里同时训练同一个任务的不同 prompt

####### （即采用多种不同方<br/>式询问同一个问题），这样相当于训练了不同模型，比模型集成的成本小多了；

##### 指示微调（Prompt\-tuning）缺点是什么？

###### 训练难度加大。

####### 不太好训练，省了显存，但不一定省时间

####### 具体来讲，大部分prompt现在只是parameter <br/>efficient并没有达到想要的training efficient

####### 也就是说只是省了空间\(显存\)，但不一定能加快训练，训练时间<br/>有可能更长

###### 多个 prompt token 之间相互独立，可能会影响效果

###### 在NLU上，prompt tuning对于正常大小的预训练模型表现不佳；

###### 现有的prompt tuning方法不能处理困难的序列标注任务

##### 指示微调（Prompt\-tuning）与 Prefix\-tuning 区别

###### 可以看作是Prefix Tuning的简化版本

####### 1\. 适用任务不同

######## a\. Prefix\-tuning 仅针对 NLG 任务有效，服务于 GPT 架构；

######## b\. 2\.指示微调（Prompt\-tuning） 考虑所有类型的语言模型

####### 2\. 添加方式不同

######## a\. Prefix\-tuning 限定在输入前面添加

######## b\. 指示微调（Prompt\-tuning） 可以在任意位置添加

######### 但是仅token 输入的任意位置

####### 3\. prompt连续向量添加方式不同

######## a\. Prefix\-tuning 每一层都添加，保证效果

######## b\. 指示微调（Prompt\-tuning） 可以只在 输入层 添加

#####  指示微调（Prompt\-tuning）与 fine\-tuning 区别 是什么？

###### Fine\-tuning 需要改变预训练阶段模型参数， 可能带量灾难性遗忘问题

###### 指示微调（Prompt\-tuning） 不改变预训练阶段模型参数，<br/>而是通过微调寻找更好的连续 prompt token参数，来引导已学习到的知识使用

####  P\-tuning 篇

##### 为什么需要 P\-tuning？

###### 大模型的Prompt构造方式严重影响下游任务的效果

###### GPT系列AR建模在自然语言理解NLU任务上效果不好，与BERT双向语言模型相比有明显差距；

###### 自然语言理解NLU任务

####### 语义理解：

####### 意图识别

####### 情感分析

####### 词性标注

####### 命名实体识别

####### 句法分析：

###### GPT\-3采用人工构造的模版来做上下文学习（in context learning），但人工设计的模版的变化特别敏感，加<br/>一个词或者少一个词，或者变动位置都会造成比较大的变化

###### 之前的研究表明GPT3使用prompt训练方式可以显著提升few\-shot 和 zero\-shot的效果；

###### 自动化搜索模版工作成本也比较高，以前这种离散化的token的搜索出来的结果可能并不是最优的，导致性能<br/>不稳定；

##### P\-tuning 思路是什么？

###### 可学习的 Embedding层 设计。将 Prompt 转换为 可学习 Embedding层；

###### prompt encoder设计。用 prompt encoder（由一个双向的LSTM\+两层MLP组成） 的方式来对Prompt <br/>Embedding进行一层处理，建模伪token的相互依赖，并且可以提供一个更好的初始化。

##### P\-tuning 优点是什么？

###### 引入prompt encoder（由一个双向的LSTM\+两层MLP组成）来建模伪token的相互依赖，并且可以提供一个更好<br/>的初始化;
> align=`left`


##### P\-tuning 缺点是什么？

###### 复杂性增加。稍显复杂，看着不太像prompt了；

###### 伪token编码时是连续的，但在与输入结合时可能是不连续的，中间可能会插入输入

#### P\-tuning v2 

##### 为什么需要 P\-tuning v2？

###### 如何 让Prompt Tuning能够在不同参数规模的预训练模型、<br/>针对不同下游任务的结果上都达到匹敌Fine\-tuning的结果

##### P\-tuning v2 思路是什么？

###### Deep Prompt Encoding：采用 Prefix\-tuning 的做法，<br/>在输入前面的每层加入可微调的 Prompts tokens作为输入；

###### 移除了重参数化的编码器（prefix\-tuning中可选的MLP、p\-tuning中的LSTM）

####### prefix\-tuning 和 ptuning，通过利用重参数化功能来提高训练速度和鲁棒性，但是<br/>该方法对于较小的模型，同时还会影响模型<br/>的表现；

###### 针对不同任务采用不同的提示长度。

####### 提示长度在提示优化方法的超参数搜索中起着核心作用。在实验中，发现不同的理解任务通常用不同的<br/>提示长度来实现其最佳性能，这与Prefix\-Tuning中的发现一致，不同的文本<br/>生成任务可能有不同的最佳提示长度；
> align=`left`


##### P\-tuning v2 优点是什么？

###### 在输入前面的每层加入可微调的 Prompts tokens作为输入

####### a\. 更多可学习的参数（从P\-tuning和Prompt Tuning的0\.01%增加到0\.1%\-3%），同时也足够参数高效；

####### b\. 加入到更深层结构中的Prompt能给模型预测带来更直接的影响；

###### 2\. 解决了Prompt Tuning无法在小模型上有效提升的问题；

###### 3\. 将Prompt Tuning拓展至NER等序列标注任务上

###### 引入多任务学习，先在多任务的prompt上进行预训练，然后再适配下游任务；

###### 5\. 抛弃了prompt learing中常用的verbalizer，回归到传统的CLS和token label分类范式

##### 4\.4\.4 P\-tuning v2 缺点是什么？

###### 抛弃了prompt learing中常用的verbalizer，回归到传统的CLS和token label分类范式，这其实某种程度上弱化了<br/>prompt的味道
