[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 43\-显存优化策略篇
> mmd.emoticon=`tree`


## 一、介绍一下 gradient accumulation 显存优化方式？

### 正常情况下是一个batch之后统一计算梯度大小

### gradient accumulation可以再指定多个batch之后一起更新梯度

### 这种情况下，可以在batch\_size很小的时候，提升真正的batch\_size，<br/>是一种显存占用的优化算法

### 。随着模型和<br/>数据规模越来越大

#### 显存紧张的时候，需要把batch\_size设置的很小，

#### 使用gradient accumulation的技术可以在<br/>实际上提高真正的batch\_size

##### e【如果batch\_size很小的话，会导致训练不稳定，收敛更慢】

### 梯度累积（Gradient Accumulation）是深度学习训练中的一种技术

#### 用于在一次反向传播（backpropagation）<br/>中累积多个小批量数据的梯度，然后一次性更新模型参数

#### 这个技术的主要目的是在内存有限的情况下，能够有<br/>效地使用大批量数据进行训练，从而提高模型性能

### \.\.\. 其他内容

#### 实战代码

##### 如何做

## 二、介绍一下 gradient checkpointing 显存优化方式？

### 梯度检查点（Gradient Checkpointing）<br/>是一种优化深度学习模型训练中内存使用的技术

#### 通过在模型的计算<br/>图中插入检查点，将一部分计算推迟到后续步骤进行，<br/>从而减少内存占用。

#### 有助于训练更大、更深的模型，以<br/>及使用更大批量的数据，而无需占用大量的内存

### 梯度检查点是一种用于优化深度学习模型训练中内存使用的技术，<br/>通过延迟部分计算和存储中间结果，减少了反向传播过程<br/>中的内存需求，从而支持更大规模的模型和数据。

#### 梯度检查点技术虽然在内存管理方面提供了优势，<br/>但同时也会引入一些计算开销，因为需要在前<br/>向传播过程中存储和管理检查点。
