[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# nn\.DataParallel篇
> mmd.emoticon=`tree`


## 为什么需要nn\.DataParallel？

### 多GPU并行训练的原理就是将模型参数和数据分布到多个GPU上

### 同时利用多个GPU计算加速训练过程。具体<br/>实现需要考虑以下两个问题：

#### 数据如何划分？

##### 数据并行：

###### 将数据分割成多个小批次，每个GPU处理其中的一个小批次

###### 然后将梯度汇总后更新模型参数。

##### 模型并行：

###### 将模型分解成多个部分，每个GPU处理其中一个部分

###### 并将处理结果传递给其他GPU以获得最终<br/>结果。

#### 计算如何协同？

##### 每个GPU都需要计算模型参数的梯度并将其发送给其他GPU

##### 因此需要使用同步机制来保<br/>证计算正确性。一般有两种同步方式：

###### 数据同步

####### 在每个GPU上计算模型参数的梯度，<br/>然后将梯度发送到其他GPU上进行汇总，<br/>最终更新模型参数。

###### 模型同步

####### 在每个GPU上计算模型参数的梯度，然后将模型参数广播到其他GPU上进行汇总，<br/>最终更新模型参数。

## 一、pytorch中的GPU操作默认是什么样？

### pytorch中的GPU操作默认是异步的

### Pytorch中的多GPU并行计算是数据级并行，相当于开了多个进程，<br/>每个进程自己独立运行，然后再整合在一起。

#### device\_ids = \[0, 1\]<br/> net = torch\.nn\.DataParallel\(net, device\_ids=device\_ids\)
> align=`left`


## 二、介绍一下 nn\.DataParallel 函数？

### 函数参数：

#### module：

##### 即模型，此处注意，虽然输入数据被均分到不同gpu上，但每个gpu上都要拷贝一份模型；

#### device\_ids

##### 即参与训练的gpu列表，例如三块卡， device\_ids = \[0，1，2\]；

#### output\_device：

##### 指定输出gpu，一般省略。在省略的情况下，默认为第一块卡，即索引为0的卡。此<br/>处有一个问题，输入计算是被几块卡均分的，但输出loss的计算是由这一张卡独自承担的，这就造成<br/>这张卡所承受的计算量要大于其他参与训练的卡。
