[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 69\-大模型幻觉（LLM Hallucination）面
> mmd.emoticon=`tree`


## 一、什么是大模型幻觉？

### 在语言模型的背景下，幻觉指的是一本正经的胡说八道：<br/>看似流畅自然的表述，<br/>实则不符合事实或者是错误的。

## 二、为什么LLM会产生幻觉？

### 1\. 源与目标的差异：

#### 在存在源与目标差异的数据上训练模型时

##### 模型产生的文本可能与原始源内容产生<br/>偏差

#### 可能是在数据收集过程中不经意间产生的，有时则是故意为之

### 4\. 训练数据的重复性：

#### 训练过程中使用的数据，如果存在大量重复

#### 可能导致模型在生成时过于偏好某些高频<br/>短语，这也可能引发“幻觉”

### 5\. 数据噪声的影响：

#### 使用充斥噪声的数据进行训练，往往是导致“幻觉”出现的关键因素之一。

### 6\. 解码过程中的随机性：

#### 在增加输出多样性的解码策略，如top\-k采样、top\-p方法以及温度调节，有时会<br/>增加“幻觉”的产生

## 三、为什么需要解决LLM的幻觉问题？

### LLMs的幻觉可能会产生如传播错误信息或侵犯隐私等严重后果

## 四、幻觉一定是有害的吗？

### 幻觉不一定是有害的，特别是在一些需要创造力或灵感的场合

#### ，比如写电影剧情

### ，对幻觉的容忍度取决于具体的应用场景。

## 五、幻觉有哪些不同类型？

### • 内在幻觉：生成的内容与源内容相矛盾。

### • 外部幻觉：生成的内容不能从源内容中得到验证，既不受源内容支持也不受其反驳。

## 六、如何度量幻觉？

### 最有效可靠的方式当然是靠人来评估，但是人工评估的成本太高了。因此有了一些自动化评估的指标：

### • 命名实体误差：

#### 命名实体（NEs）是“事实”描述的关键组成部分

#### 一个模型生成了不在原始知识源中的NE，那么它可以被视为产生了幻觉<br/>（或者说，有事实上的错误）。

### • 蕴含率：该

#### 被参考文本所蕴含的句子数量与生成输出中的总句子数量的比例。

### • 基于模型的评估：应对复杂的句法和语义变化。

### • 利用问答系统：

#### 问答<br/>模型将使用原始的参考文本来回答这些问题，并计算所得答案的相似性

### • 利用信息提取系统：

#### 从生成的文本中提取此类元组，并与从原始材料中提取的元组进行比较

## 七、如何缓解LLM幻觉？

### 通过创建高质量无噪声的数据集来解决

### 但是，验证和清理数百GB<br/>的文本语料库难度太大了。

#### 因此也有了一些其他的方法：

##### • 利用外部知识验证正确性

##### • 修改解码策略

##### • 采样多个输出并检查其一致性

### 7\.1 通过使用外部知识验证主动检测和减轻幻觉

#### 在检测阶段，

##### 首先确定潜在幻觉的候选者，即生成句子的重要概念。<br/>然后，利用其logit分数输出值计算模型对它们的<br/>不确定性并检索相关知识。

#### 在减轻阶段

##### 使用检索到的知识作为证据修复幻觉句子。<br/>将修复的句子附加到输入（和之前生成的句子）上，并<br/>继续生成下一个句子。这个过程不仅减轻了检测到的幻觉，<br/>而且还阻止了其在后续生成的句子中的传播。

### 7\.2 事实核心采样

#### 该算法在生成每个句子时动态调整“核心”p。<br/>在事实核心采样中，生成每个句子的第t个标记的核心概率pt<br/>为

##### 生成句子的后面， 其多样性概率降低

### 7\.3 SelfCheckGPT

#### 从模型中采样多个response（比如通过变化温度参数）<br/>并测量不同response之间的信息一致性，以确<br/>定哪些声明是事实，哪些是幻觉。

## 八、LLMs什么时候最容易产生幻觉？

### • 数值混淆：

#### 处理与数字有关的文本，如日期或数值时，容易产生幻觉。

### • 处理长文本：

#### 在需要解读长期依赖关系的任务中，例如文档摘要或长对话历史，模型可能会生成自相矛盾的<br/>内容。

### • 逻辑推断障碍：

#### 若模型误解了源文本中的信息，它有可能产生不准确的结论

### • 上下文与内置知识的冲突：

#### 可能会过度依赖于预训练阶段获取的知识，而忽略实际上下<br/>文，导致输出不准确。

### • 错误的上下文信息：

#### 当给定的上下文包含错误信息或基于错误的假设时
