[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 75\-GPT 经验篇
> mmd.emoticon=`tree`


## 三、bert和gpt有什么区别

### BERT是一个双向编码器，它预测输入序列中的缺失部分，因此可以用于多种任务，如文本分类、<br/>命名实体识别等

### GPT是一个单向解码器，它生成文本的下一个单词，因此主要用于生成型任务，如文本生成、对话<br/>生成等。

## 四、文本生成的几大预训练任务？

### • GPT（Generative Pre\-trained Transformer）系列：包括GPT、GPT\-2、GPT\-3等。这些模型<br/>使用Transformer架构进行预训练，在大规模语料上学习语言模型，能够生成连贯、具有语义的<br/>文本。

### • BART（Bidirectional and Auto\-Regressive Transformer）：BART是一种基于Transformer的生<br/>成式预训练模型。它通过自回归解码器实现文本生成，通过自编码器预训练目标来重构输入文<br/>本，能够生成流畅、连贯的文本。

### • T5（Text\-to\-Text Transfer Transformer）：T5是一种通用的文本生成模型，使用了编码器\-解码<br/>器结构。它将不同的自然语言处理（NLP）任务转换为文本到文本的转换任务，<br/>可用于机器翻译、摘要生成、问题回答等多个NLP任务。

### • XLNet：

#### XLNet是一种基于Transformer架构的预训练模型，采用了自回归和自编码器的组合方<br/>式进行训练。它在语言建模任务上引入了全局的上下文信息，能够生成更加准确和连贯的文<br/>本。

### • UniLM（Unified Language Model）

#### UniLM是一种多任务学习的预训练模型，将不同的自然语<br/>言处理任务转化为统一的生成式任务。它可以用于文本摘要、问答系统、机器翻译等多个任<br/>务
