[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 78\-小样本提示学习篇
> mmd.emoticon=`tree`


## 一、什么是Zero\-shot提示方法？

### Zero\-shot提示方法是指给模型提供一个不属于训练数据的提示

#### 但模型可以生成你期望的结果的方法。

#### 这种方法<br/>使得大型语言模型可以用于许多任务

### zero\-shot可以理解为：不给大模型任何的提示，直接提问，让大模型自己做决策。

## 二、什么是Few\-shot提示方法？

### Few\-shot提示方法是指给模型提供一些示例或上下文，来引导模型更好地完成任务的方法

### 这些示例或上下文可<br/>以作为模型的条件，来影响后续的输出

#### 例如，

##### 你可以给模型一些情感分析的示例，让它根据文本判断情感倾<br/>向

##### 或者给模型一些编程任务的示例，让它生成代码片段

### 可以简单理解为：在提问之前，先给大模型一个示例<br/>和解释让它学习和模仿，从而在一定程度上赋予它泛化能力。

## 三、阐述One\-shot和Few\-shot<br/>提示策略及其应用场景？

### One\-shot或者Few\-shot提示方法的思想：

#### One\-shot提示策略

##### 是指只给模型一个示例或上下文的方法。

##### 这种方法适用于一些相对简单<br/>或常见的任务，或者一些模型已经有了很强的涌现能力的任务

##### 例如

###### 你可以给模型一个新词和它的定义，然后<br/>让它用这个新词造句。

#### Few\-shot提示策略

##### 是指给模型多个示例或上下文的方法

##### 这种方法适用于一些相对复杂或<br/>特殊的任务，或者一些模型需要更多的引导和调整的任务。

##### 例如

###### 可以给模型几个不同类型的笑话，然后让它<br/>根据一个关键词生成一个新的笑话。

##### 具体的应用来说，

###### Few\-shot提示方法并不复杂，只需要将一些类似的问题的<br/>问题\+答案作为prompt的一部分进行输入即可

##### 当需要输入多段问答作为提示词时，以Q作为问题的开头、A作为<br/>回答的开头（也可以换成“问题”、“答案”）

##### 并且不同的问答对话需要换行以便于更加清晰的展示，具体方法是<br/>通过转义符\+换行来完成。

## 四、什么是逐步Zero\-shot

### 指一种利用大型语言模型进行推理的方法，它通过让模型自动生成多个中间步骤或过程，然后<br/>再根据这些步骤或过程来生成结果。

### 逐步 Zero\-shot 可以让模型更好地理解问题的含义和范围，更接近人类的思<br/>考方式

### 在论文Large Language Models are Zero\-Shot Reasoners中，<br/>提出了“逐步 Zero\-shot”这一思想

#### 在第一个阶段

##### 模型首先对问题进行拆分并分段解答问题（称为Reasoning Extraction）

#### 在第二阶段

##### 模型再进行答案的汇总（称为Answer Extraction）。

## 五、定义Zero\-shot\-CoT提示策略并描述其应用方法？

### 是指一种利用 Zero\-shot 思维链进行推理的方法，该方法借助思维链（也被称为思考<br/>链，Chain of Thought，CoT）提示法来解决问题

### 通过在问题的结尾附加“Let’s think step by step”<br/>这几个词，来引导模型生成一个回答问题的思维链。

### Zero\-shot\-CoT 提示策略可以让模型更有效地利用其通用知<br/>识和涌现能力，同时避免过拟合或灾难性遗忘。

### Zero\-shot\-CoT 提示策略的应用方法如下：

#### 1\. 首先，明确你想要解决的问题或任务，以及你期望的输出或回答的格式和内容。

#### 2\. 然后，将你的问题或任务用自然语言描述出来，<br/>并在结尾加上“Let’s think step by step”这几个词，作为输入<br/>或查询给模型。

#### 3\. 最后，观察模型生成的输出或回答，看是否符合你的期望和需求。<br/>如果不满意，可以尝试修改你的输入或查<br/>询，或者使用其他控制参数来影响模型的行为。

### 例如，你可以使用 Zero\-shot\-CoT <br/>提示策略来解决一个简单的数学应用题：

#### 提示 我去市场买了 10 个苹果。我给邻居 2 个苹果，给修理工 2 个苹果。然后我又买了 5 个苹果，并吃了 1<br/>个。我还剩下多少个苹果？Let’s think step by step\.<br/>输出 首先，你开始有 10 个苹果。你送走了 2 个苹果给邻居和 2 个苹果给修理工，所以你还剩下 6 个苹果。然后<br/>你又买了 5 个苹果，所以现在你有 11 个苹果。最后，你吃了 1 个苹果，所以你还剩下 10 个苹果。
