[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# NLP Trick 篇
> mmd.emoticon=`tree`


## 一、怎么处理类别不平衡？

### 类别不平衡问题可以通过过采样、欠采样、生成新样本、集成学习等方法来解决

### 过采样方法包括随机过采样、SMOTE等

### 欠采样方法包括随机欠采样、Tomek Links等

### 生成新样本方法包括GAN、VAE等；

### 集成学习方法包<br/>括Bagging、Boosting等。

#### 集成学习方法在构建基学习器时会对训练数据进行重新采样。<br/>例如，在 Bagging 方法中，可以采用过采样（对少数类样本进行复制）<br/>或欠采样（对多数类样本进行删减）的方式来平衡每个基学习器的训练数据集

## 二、有了解其他模型去尝试解决长度限制的方案吗？

### Bert模型的长度限制问题主要是由于Transformer结构中的<br/>自注意力机制（self\-attention mechanism）和位置嵌<br/>入（position embeddings）所导致的

#### 这些机制使得Bert对于较长的序列处理非常耗时，<br/>并且占用大量的内存，<br/>从而限制了Bert在处理长序列任务上的性能。

### 模型有一定的输入长度限制，通常是 512 个 token，解决其长度限制问题主要有以下几种方法

### 智能截断

#### 采用基于语义的截断方法。

##### 优先保留包含主要语义成分（如主语、谓语、宾语）的部分

##### 对于对话文本，根据对话轮次的重要性进行截断

### 动态填充

#### 可以根据具体任务和输入文本的分布情况，动态地调整填充策略

#### 对于长度分布在 300 \- 400 token 的文本，将输入长度调整为 400，这样可以减少不必要的填充

### 二、模型架构改进

#### 在 BERT 的基础上，添加类似于 Transformer \- XL 的相对位置编码和记忆模块

#### • Longformer：

##### Sliding Window Attention"，<br/>该机制可以在处理长序列时缓解Bert模型的计算和存储成本

#### • Reformer：

##### 基于哈希注意力（Hashing Attention）的Transformer模型

##### 可以有效地<br/>处理长序列，并且在一些NLP任务上表现良好。

#### • Performer：

##### 基于FFT（Fast Fourier Transform）的Transformer模型

###### 该模型可以处理长序<br/>列

#### • Sparse Transformer：

##### ：Sparse Transformer是一种使用稀疏注意力机制的Transformer模型

##### 它可以减少Bert<br/>模型在处理长序列时的计算和存储成本。

### 三、文本分割与拼接策略

#### 滑动窗口法

##### 将长文本分割成多个重叠的窗口。

###### 例如，对于一个 1000 个 token 的长文本，窗口大小设为 256，步长设为 128。<br/>这样每个窗口之间有部分重叠，能够保证信息的连续性

##### 然后，对每个窗口进行 BERT 处理，得到每个窗口的特征表示。<br/>最后，通过某种方式（如加权平均或拼接后再经过一个全连接层）将这些窗口的特征表示合并成一个完整的长文本特征表示。

#### 层次化分割法

##### 按照文本的结构进行分割，如对于文档可以先按照段落分割，对于段落可以按照句子分割

##### 先对每个句子或段落进行 BERT 处理，得到它们的特征表示。<br/>然后，通过一个更高层次的模型（如另一个 Transformer 层或者简单的神经网络）将这些句子或段落的特征表示进行组合，<br/>以得到整个长文本的特征表示。这样可以逐步处理长文本，避免直接处理过长的序列。
